[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rlox"
path = "src/bin/rlox/main.rs"

[[bin]]
name = "create_ast"
path = "src/bin/create_ast.rs"

[dependencies]
colored = "2.1.0"
